spring.application.name=payment-system

server.port=8080

spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.swagger-ui.path=/swagger-ui.html
logging.level.root=INFO
spring.devtools.restart.enabled=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Retry Configuration

resilience4j.retry.instances.paymentGateway.max-attempts=3
resilience4j.retry.instances.paymentGateway.wait-duration=1s
resilience4j.retry.instances.paymentGateway.enable-exponential-backoff=true
resilience4j.retry.instances.paymentGateway.exponential-backoff-multiplier=2

# Circuit Breaker Configuration

resilience4j.circuitbreaker.instances.paymentGateway.register-health-indicator=true

resilience4j.circuitbreaker.instances.paymentGateway.sliding-window-size=5

resilience4j.circuitbreaker.instances.paymentGateway.minimum-number-of-calls=5

resilience4j.circuitbreaker.instances.paymentGateway.failure-rate-threshold=50

resilience4j.circuitbreaker.instances.paymentGateway.wait-duration-in-open-state=15s

resilience4j.circuitbreaker.instances.paymentGateway.permitted-number-of-calls-in-half-open-state=2

resilience4j.circuitbreaker.instances.paymentGateway.automatic-transition-from-open-to-half-open-enabled=true